-- ANÁLISE REMESSA X QTD DEVOLVIDA
SELECT
    A.INVOICE_NUMBER NF_REMESSA,
    B.SEGMENT1,
    A.RECEIVING_DATE DATA_RECEBIMENTO_REM,
    A.RECEIVED_QUANTITY QUANTIDADE_RECEBIDA,
    A.REMAINING_BALANCE QUANTIDADE_RESTANTE,
    (SELECT SUM(DEVOLUTION_QUANTITY) FROM CLL_F513_TPA_DEVOLUTIONS_CTRL D WHERE  D.TPA_RECEIPTS_CONTROL_ID = A.TPA_RECEIPTS_CONTROL_ID)QTD_DEV,
    (RECEIVED_QUANTITY - REMAINING_BALANCE - (SELECT SUM(DEVOLUTION_QUANTITY) FROM CLL_F513_TPA_DEVOLUTIONS_CTRL D WHERE  D.TPA_RECEIPTS_CONTROL_ID = A.TPA_RECEIPTS_CONTROL_ID)) DIFERENÇA,
    (SELECT LISTAGG(C.TRX_NUMBER ||'('||C.DEVOLUTION_QUANTITY||')', ',')
     WITHIN GROUP  (ORDER BY C.TRX_NUMBER)
     FROM CLL_F513_TPA_DEVOLUTIONS_CTRL C WHERE  C.TPA_RECEIPTS_CONTROL_ID = A.TPA_RECEIPTS_CONTROL_ID 
     GROUP BY A.INVOICE_NUMBER,
              B.SEGMENT1,
              A.RECEIVING_DATE,
              A.RECEIVED_QUANTITY,
              A.REMAINING_BALANCE
    )                   NF_DEV
    
FROM
    cll_f513_tpa_receipts_control A
JOIN MTL_SYSTEM_ITEMS_B B ON  A.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID AND A.ORGANIZATION_ID = B.ORGANIZATION_ID

WHERE RECEIVED_QUANTITY IS NOT NULL
ORDER BY A.RECEIVING_DATE DESC;
