SET SERVEROUTPUT ON;
DECLARE
VDEVCONTROLID  NUMBER;
vValida NUMBER := 0;
CURSOR C_SUBINVENTORY IS
                    SELECT TPA_DEVOLUTIONS_CONTROL_ID 
                    FROM CLL_F513_TPA_DEVOLUTIONS_CTRL 
                    WHERE SUBINVENTORY IS NULL 
                    AND DEVOLUTION_STATUS = 'INVENTORY PENDING';
		R_SUBINVENTORY C_SUBINVENTORY%ROWTYPE;
BEGIN
FOR R_SUBINVENTORY IN C_SUBINVENTORY
LOOP
    VDEVCONTROLID := R_SUBINVENTORY.TPA_DEVOLUTIONS_CONTROL_ID;
    
    UPDATE CLL_F513_TPA_DEVOLUTIONS_CTRL
    SET SUBINVENTORY = 'TERC_KMB'
    WHERE TPA_DEVOLUTIONS_CONTROL_ID = VDEVCONTROLID;
    DBMS_OUTPUT.PUT_LINE(VDEVCONTROLID);
    
EXIT WHEN C_SUBINVENTORY%NOTFOUND;
END LOOP;
END;

SELECT TPA_DEVOLUTIONS_CONTROL_ID , SUBINVENTORY
                    FROM CLL_F513_TPA_DEVOLUTIONS_CTRL 
                    WHERE TPA_DEVOLUTIONS_CONTROL_ID = 7403
                    AND DEVOLUTION_STATUS = 'INVOICE PENDING';