--RELATÓRIO RASTREIO PLANO DIÁRIO V.3
SELECT 
    A.WIP_ENTITY_ID,
    A.WIP_ENTITY_NAME OP_KMB,
    O.MEANING STATUS_OP_KMB,
    A.CD_ITEM MODELO,
    A.NR_CHASSI,
    E.SEGMENT1 ITENS,
    A.DT_PRODUCAO,
    A.CREATION_DATE DT_CRIAÇÃO,
    D.SEGMENT1 REQ_KMB,
    D.AUTHORIZATION_STATUS,
    SUBSTR(D.DESCRIPTION,28,3) TIPO_ORDEM,
    G.SEGMENT1 OC_KMB,
    H.ORDER_NUMBER OV_KCA,
    H.FLOW_STATUS_CODE,
    L.WIP_ENTITY_NAME OP_KCA,
    M.MEANING STATUS_OP_KCA

FROM 
    DTT_WIP_PROGRAMACAO_OP_V A
    
    JOIN WIP_DISCRETE_JOBS N ON A.WIP_ENTITY_ID = N.WIP_ENTITY_ID
    JOIN FND_LOOKUP_VALUES_VL O ON TO_CHAR(N.STATUS_TYPE) = O.LOOKUP_CODE
    LEFT JOIN PO_REQUISITION_HEADERS_ALL D ON A.NR_CHASSI = D.ATTRIBUTE2 -- VINCULO DA ASSOCIAÇÃO WIP COM AS LINHAS DA REQUISIÇÃO
    JOIN PO_REQUISITION_LINES_ALL F ON D.REQUISITION_HEADER_ID = F.REQUISITION_HEADER_ID -- VINCULO REQ LINHA COM HEADER
    JOIN MTL_SYSTEM_ITEMS_B  E ON F.ITEM_ID = E.INVENTORY_ITEM_ID -- VINCULO DO ITEM REQ COM MTL_SYSTEM
    
    LEFT JOIN PO_HEADERS_ALL G ON D.SEGMENT1 = G.INTERFACE_SOURCE_CODE -- VINCULO REQ COM OC
    
    LEFT JOIN OE_ORDER_HEADERS_ALL H ON D.SEGMENT1 = H.ORIG_SYS_DOCUMENT_REF -- VINCULO OV com REQUISIÇÃO
    JOIN OE_ORDER_LINES_ALL I ON H.HEADER_ID = I.HEADER_ID
    LEFT JOIN WIP_DISCRETE_JOBS K ON I.LINE_ID = K.SOURCE_LINE_ID
    JOIN FND_LOOKUP_VALUES_VL M ON TO_CHAR(K.STATUS_TYPE) = M.LOOKUP_CODE
    LEFT JOIN WIP_ENTITIES L ON K.WIP_ENTITY_ID = L.WIP_ENTITY_ID

WHERE   A.ORGANIZATION_ID = '149'
AND     E.ORGANIZATION_ID = '149'
AND     I.INVENTORY_ITEM_ID = F.ITEM_ID
/*AND   a.wip_entity_name in ('350893',                    -- PESQUISAR POR OP
'350894',
'350895',
'350896',
'350897',
'350898',
'350899',
'350900',
'350901',
'350902',
'350903')*/
--AND  a.creation_date BETWEEN '07/04/2022' AND '08/04/2022'   -- DATA DE CRIAÇÃO
AND    A.DT_PRODUCAO BETWEEN '07/06/2022' AND '09/06/2022'     -- DATA DE PRODUÇÃO
AND    A.CD_ITEM = 'LE650H-B3A1 VERDE'                         -- PESQUISA PELO MODELO
AND    M.LOOKUP_TYPE            = 'WIP_JOB_STATUS'
AND    O.LOOKUP_TYPE            = 'WIP_JOB_STATUS'
AND    D.AUTHORIZATION_STATUS = 'APPROVED'
ORDER BY A.WIP_ENTITY_NAME;