SELECT * FROM PO_HEADERS_ALL WHERE SEGMENT1 = '17017' ;
SELECT * FROM PO_LINES_ALL WHERE PO_HEADER_ID = '996813'; 
SELECT * FROM PO_DISTRIBUTIONS_ALL WHERE PO_HEADER_ID = '996813' ;
SELECT * FROM PO_LINE_LOCATIONS_ALL WHERE PO_HEADER_ID = '996813';
SELECT * FROM CLL_F189_INVOICE_LINES WHERE line_location_id = '3090385';
SELECT * FROM ORG_ORGANIZATION_DEFINITIONS;
SELECT * FROM MTL_SYSTEM_ITEMS_B;

SELECT DISTINCT
PHA.SEGMENT1 PEDIDO,
OOD.ORGANIZATION_CODE ORG,
PHA.CLOSED_CODE STATUS,
MSIB.SEGMENT1 ITEM,
MSIB.DESCRIPTION DESCRIÇÃO,
PLA.QUANTITY QTD,
PLA.UNIT_PRICE PREÇO_UNITARIO,
PHA.CREATION_DATE DATA_PEDIDO,
PDA.QUANTITY_DELIVERED NUMERO_ENTREGA,
PLLA.PROMISED_DATE PREVISAO_ENTRADA,
CFEO.RECEIVE_DATE,
CFI.FIRST_PAYMENT_DATE DATA_PAGAMENTO,
CFI.INVOICE_NUM NOTA_FISCAL,
ASP.VENDOR_NAME,
ROUND(PLA.UNIT_PRICE * PLA.QUANTITY,2) VALOR_LIQUIDO,
PPX.FIRST_NAME

FROM
PO_HEADERS_ALL PHA,
PO_LINES_ALL PLA,
PO_DISTRIBUTIONS_ALL PDA,
PO_LINE_LOCATIONS_ALL PLLA,
CLL_F189_INVOICE_LINES CFIL,
CLL_F189_INVOICES CFI,
CLL_F189_ENTRY_OPERATIONS CFEO,
ORG_ORGANIZATION_DEFINITIONS OOD,
MTL_SYSTEM_ITEMS_B MSIB,
AP_SUPPLIERS ASP,
PER_PEOPLE_X PPX

WHERE
    PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
AND PLA.PO_HEADER_ID = PDA.PO_HEADER_ID
AND PDA.PO_HEADER_ID = PLLA.PO_HEADER_ID
AND PLLA.LINE_LOCATION_ID = CFIL.LINE_LOCATION_ID
AND CFI.OPERATION_ID = CFEO.OPERATION_ID
AND CFI.ORGANIZATION_ID = CFEO.ORGANIZATION_ID
AND CFI.LOCATION_ID = CFEO.LOCATION_ID
AND CFI.INVOICE_ID = CFIL.INVOICE_ID
AND OOD.ORGANIZATION_ID = PLLA.SHIP_TO_ORGANIZATION_ID 
AND ASP.VENDOR_ID = PHA.VENDOR_ID
AND PPX.PERSON_ID = PDA.DELIVER_TO_PERSON_ID
AND PLA.ITEM_ID = MSIB.INVENTORY_ITEM_ID
AND PHA.SEGMENT1 = '16339'