--ENVIO INVOICE
SELECT
    nfe0_.nf_id                            AS nf_id1_10_0_,
    nfe0_.nf_afrmm                         AS nf_afrmm2_10_0_,
    nfe0_.nf_marca_volume                  AS nf_marca_volume3_10_0_,
    nfe0_.nf_basecofins                    AS nf_basecofins4_10_0_,
    nfe0_.nf_baseicms                      AS nf_baseicms5_10_0_,
    nfe0_.nf_baseicms_outras               AS nf_baseicms_outras6_10_0_,
    nfe0_.nf_base_tot_icms_nfe             AS nf_base_tot_icms_n7_10_0_,
    nfe0_.nf_base_ii                       AS nf_base_ii8_10_0_,
    nfe0_.nf_baseipi                       AS nf_baseipi9_10_0_,
    nfe0_.nf_basepis                       AS nf_basepis10_10_0_,
    nfe0_.nf_cdtran                        AS nf_cdtran58_10_0_,
    nfe0_.nf_di_cod_ibge_importador        AS nf_di_cod_ibge_im11_10_0_,
    nfe0_.nf_di_local_urf_despacho         AS nf_di_local_urf_d12_10_0_,
    nfe0_.nf_di_uf_urf_despacho            AS nf_di_uf_urf_desp13_10_0_,
    nfe0_.nf_clifor                        AS nf_clifor59_10_0_,
    nfe0_.nf_ii                            AS nf_ii14_10_0_,
    nfe0_.nf_data_desembaraco              AS nf_data_desembara15_10_0_,
    nfe0_.nf_numero_di                     AS nf_numero_di16_10_0_,
    nfe0_.nf_numero_dire                   AS nf_numero_dire17_10_0_,
    nfe0_.nf_numero_nf_externo             AS nf_numero_nf_exte18_10_0_,
    nfe0_.nf_empresa                       AS nf_empresa60_10_0_,
    nfe0_.nf_nfe_sefaz_exerc_contabil      AS nf_nfe_sefaz_exer19_10_0_,
    nfe0_.nf_nfe_sefaz_cnpj                AS nf_nfe_sefaz_cnpj20_10_0_,
    nfe0_.nf_observacao                    AS nf_observacao21_10_0_,
    nfe0_.nf_pesobr                        AS nf_pesobr22_10_0_,
    nfe0_.nf_nfe_sefaz_numero_nf           AS nf_nfe_sefaz_nume23_10_0_,
    nfe0_.nf_veiculo_placa                 AS nf_veiculo_placa24_10_0_,
    nfe0_.nf_frete_ed                      AS nf_frete_ed25_10_0_,
    nfe0_.nf_cod_processo                  AS nf_cod_processo26_10_0_,
    nfe0_.nf_pesoli                        AS nf_pesoli27_10_0_,
    nfe0_.nf_nfe_sefaz_chave_acesso        AS nf_nfe_sefaz_chav28_10_0_,
    nfe0_.nf_obscancel                     AS nf_obscancel29_10_0_,
    nfe0_.nf_numnf                         AS nf_numnf30_10_0_,
    nfe0_.nf_qtde_volume                   AS nf_qtde_volume31_10_0_,
    nfe0_.nf_razao_social_transp_local     AS nf_razao_social_t32_10_0_,
    nfe0_.nf_data_registro_di              AS nf_data_registro_33_10_0_,
    nfe0_.nf_veiculo_rntc                  AS nf_veiculo_rntc34_10_0_,
    nfe0_.nf_nfe_sefaz_serie_nf            AS nf_nfe_sefaz_seri35_10_0_,
    nfe0_.nf_data_conhecimento             AS nf_data_conhecime36_10_0_,
    nfe0_.nf_especie_volume_descricao      AS nf_especie_volume37_10_0_,
    nfe0_.nf_veiculo_uf                    AS nf_veiculo_uf38_10_0_,
    nfe0_.nf_estado                        AS nf_estado39_10_0_,
    nfe0_.nf_vrmerca                       AS nf_vrmerca40_10_0_,
    nfe0_.nf_di_insc_suframa_importador    AS nf_di_insc_sufram41_10_0_,
    nfe0_.nf_vrt_cofins                    AS nf_vrt_cofins42_10_0_,
    nfe0_.nf_vricms                        AS nf_vricms43_10_0_,
    nfe0_.nf_outraicms                     AS nf_outraicms44_10_0_,
    nfe0_.nf_vlr_tot_icms_nfe              AS nf_vlr_tot_icms_n45_10_0_,
    nfe0_.nf_vripi                         AS nf_vripi46_10_0_,
    nfe0_.nf_vrt_pis                       AS nf_vrt_pis47_10_0_,
    nfe0_.nf_tpnota                        AS nf_tpnota48_10_0_,
    nfe0_.nf_nfe_sefaz_formato_danfe       AS nf_nfe_sefaz_form49_10_0_,
    nfe0_.nf_natope_descricao              AS nf_natope_descric50_10_0_,
    nfe0_.nf_dtemis                        AS nf_dtemis51_10_0_,
    nfe0_.nf_viatra                        AS nf_viatra52_10_0_,
    nfe0_.nf_numero_volume                 AS nf_numero_volume53_10_0_,
    nfe0_.nf_vrfrete                       AS nf_vrfrete54_10_0_,
    nfe0_.nf_vrseguro                      AS nf_vrseguro55_10_0_,
    nfe0_.nf_vrtotal                       AS nf_vrtotal56_10_0_,
    nfe0_.nf_nfe_sefaz_mes                 AS nf_nfe_sefaz_mes57_10_0_,
    nfempresa1_.cod_parceiro               AS cod_parceiro1_7_1_,
    nfempresa1_.nome_fantasia              AS nome_fantasia2_7_1_,
    nfempresa1_.cod_cidade_ibge            AS cod_cidade_ibge3_7_1_,
    nfempresa1_.cidade                     AS cidade4_7_1_,
    nfempresa1_.obs                        AS obs5_7_1_,
    nfempresa1_.cod_pais                   AS cod_pais6_7_1_,
    nfempresa1_.cnpj                       AS cnpj7_7_1_,
    nfempresa1_.inscricao_estadual         AS inscricao_estadual8_7_1_,
    nfempresa1_.razao_social               AS razao_social9_7_1_,
    nfempresa1_.bairro_parc                AS bairro_parc10_7_1_,
    nfempresa1_.numero                     AS numero11_7_1_,
    nfempresa1_.tel_parc                   AS tel_parc12_7_1_,
    nfempresa1_.estado                     AS estado13_7_1_,
    nfempresa1_.logradouro                 AS logradouro14_7_1_,
    nfempresa1_.cep                        AS cep15_7_1_,
    nfempresa2_.cod_parceiro               AS cod_parceiro1_7_2_,
    nfempresa2_.nome_fantasia              AS nome_fantasia2_7_2_,
    nfempresa2_.cod_cidade_ibge            AS cod_cidade_ibge3_7_2_,
    nfempresa2_.cidade                     AS cidade4_7_2_,
    nfempresa2_.obs                        AS obs5_7_2_,
    nfempresa2_.cod_pais                   AS cod_pais6_7_2_,
    nfempresa2_.cnpj                       AS cnpj7_7_2_,
    nfempresa2_.inscricao_estadual         AS inscricao_estadual8_7_2_,
    nfempresa2_.razao_social               AS razao_social9_7_2_,
    nfempresa2_.bairro_parc                AS bairro_parc10_7_2_,
    nfempresa2_.numero                     AS numero11_7_2_,
    nfempresa2_.tel_parc                   AS tel_parc12_7_2_,
    nfempresa2_.estado                     AS estado13_7_2_,
    nfempresa2_.logradouro                 AS logradouro14_7_2_,
    nfempresa2_.cep                        AS cep15_7_2_,
    nfempresa3_.cod_parceiro               AS cod_parceiro1_7_3_,
    nfempresa3_.nome_fantasia              AS nome_fantasia2_7_3_,
    nfempresa3_.cod_cidade_ibge            AS cod_cidade_ibge3_7_3_,
    nfempresa3_.cidade                     AS cidade4_7_3_,
    nfempresa3_.obs                        AS obs5_7_3_,
    nfempresa3_.cod_pais                   AS cod_pais6_7_3_,
    nfempresa3_.cnpj                       AS cnpj7_7_3_,
    nfempresa3_.inscricao_estadual         AS inscricao_estadual8_7_3_,
    nfempresa3_.razao_social               AS razao_social9_7_3_,
    nfempresa3_.bairro_parc                AS bairro_parc10_7_3_,
    nfempresa3_.numero                     AS numero11_7_3_,
    nfempresa3_.tel_parc                   AS tel_parc12_7_3_,
    nfempresa3_.estado                     AS estado13_7_3_,
    nfempresa3_.logradouro                 AS logradouro14_7_3_,
    nfempresa3_.cep                        AS cep15_7_3_,
    notafiscal4_.id_notafiscal             AS id_notafiscal1_3_4_,
    notafiscal4_.inscricao_estadual        AS inscricao_estadual2_3_4_
FROM
    trbskmb.v_bs_api_nfe_nfc  nfe0_
    LEFT OUTER JOIN trbskmb.sfw_parceiro      nfempresa1_ ON nfe0_.nf_cdtran = nfempresa1_.cod_parceiro
    LEFT OUTER JOIN trbskmb.sfw_parceiro      nfempresa2_ ON nfe0_.nf_clifor = nfempresa2_.cod_parceiro
    LEFT OUTER JOIN trbskmb.sfw_parceiro      nfempresa3_ ON nfe0_.nf_empresa = nfempresa3_.cod_parceiro
    LEFT OUTER JOIN trbskmb.nota_fiscal       notafiscal4_ ON nfe0_.nf_id = notafiscal4_.id_notafiscal
WHERE
    nfe0_.nf_id = 5828;
-- Cria Header
SELECT
    nfeletroni0_.codigo_nf            AS codigo_nf1_0_0_,
    nfeletroni0_.natureza_operacao    AS natureza_operacao2_0_0_,
    nfeletroni0_.transp_cnpj          AS transp_cnpj3_0_0_,
    nfeletroni0_.transp_ie            AS transp_ie4_0_0_,
    nfeletroni0_.transp_mod_frete     AS transp_mod_frete5_0_0_
FROM
    trbskmb.nf_eletronica nfeletroni0_
WHERE
    nfeletroni0_.codigo_nf = 5828;
-- Criação Itens    
SELECT
    avalaraite0_.id_nf              AS id_nf1_11_,
    avalaraite0_.num_item           AS num_item2_11_,
    avalaraite0_.lineamount         AS lineamount3_11_,
    avalaraite0_.lineunitprice      AS lineunitprice4_11_,
    avalaraite0_.num_nf             AS num_nf5_11_,
    avalaraite0_.othercostamount    AS othercostamount6_11_,
    avalaraite0_.taxcofins          AS taxcofins7_11_,
    avalaraite0_.taxii              AS taxii8_11_,
    avalaraite0_.taxpis             AS taxpis9_11_
FROM
    trbskmb.vw_avalara_item_cst avalaraite0_
WHERE
    avalaraite0_.id_nf = 5818   